extends: ["janus/ts", "janus/security", "prettier"]
plugins: ["prettier"]
ignorePatterns: ["built/**/*"]
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
rules:
  "prettier/prettier": error
