extends: ["janus/ts", "janus/security"]
# plugins: []
ignorePatterns: ["built/**/*"]
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
# rules:
#   "prettier/prettier": error
